#Script provided by Thomas Feher
#Not yet used (Sept 2016) for continuous integration by Audacity Team
#but developers who clone audacity.git can adapt and use.
#useful for Linux-only developers.
#if you want to work on this, please talk with us on
# https://lists.sourceforge.net/lists/listinfo/audacity-devel
#build time is circa 50 mins.
version: 2.1.2-{build}
shallow_clone: true # reduce traffic
install:
    # install gettext tool (only used by target "locale", which is not built at
    # the moment due to long duration
    - nuget install Gettext.Tools
    - set PATH=%PATH%;%AUDACITY_ROOT%\Gettext.Tools.0.19.7.001\tools\bin
    # download wxWidgets
    - git clone --branch v3.0.2 --depth 1 https://github.com/wxWidgets/wxWidgets.git %WXWIN%
    # apply audacity patches
    - xcopy %AUDACITY_ROOT%\win\wxWidgets_additions\wxWidgets-3.0.2 %WXWIN% /s /y /f
    - xcopy %WXWIN%\include\wx\setup_redirect.h %WXWIN%\include\wx\setup.h* /f
    # build wxWidgets
    - msbuild %WXWIN%\build\msw\wx_vc12.sln /p:Configuration="DLL Release" /target:adv,base,core,html,net,qa,wxexpat,wxjpeg,wxpng,wxtiff,wxzlib /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
environment:
    WXWIN: c:\wxWidgets-3.0.2
    AUDACITY_ROOT: c:\projects\audacity
# replace `build_script` with `build` and `configuration` when complete build
# does not exceed a duration of 1 hour
#build:
    #project: win/audacity.sln
#configuration:
    #- Release
build_script: # build all targets except of `help` and `locale`
    msbuild win/audacity.sln /p:Configuration=Release /target:expat,filedialog,libflac++,libflac,libid3tag,libmad,libnyquist,libogg,libscorealign,libsndfile,libsoxr,libvamp,libvorbis,lv2,portaudio-v19,portmidi,portmixer,portsmf,sbsms,soundtouch,twolame,help,Audacity /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
